### ISSUE TITLE
Extension is no longer compatible with TYPO3 v7

### ISSUE THREAD

**Issue by kleintim** [Intera/typo3-extension-authcode#4]
The following commit:
https://github.com/Intera/typo3-extension-authcode/commit/55da32abbabc897e8f30d8710215884fd7d7cb37?diff=split
causes an Exception in TYPO3 v7:

Uncaught TYPO3 Exception
Class 'TYPO3\CMS\Core\Crypto\Random' not found

the change in line 399:
<code>
$authCodeString = GeneralUtility::getRandomHexString(16);
</code>
to
<code>
$authCodeString = GeneralUtility::makeInstance(Random::class)->generateRandomHexString(16);
</code>
makes this version of EXT:authcode min requirement TYPO3 v8!
Possible solutions:
new Version-Number in ext_emconf with min requirement v8
or revert change in Classes/Domain/Repository/AuthCodeRepository.php

Best regards!
Tim

**Comment by astehlik** [comment]
Hi Tim,

thank you for taking the time to create an issue.

I cleaned up the requirements now and released two new versions:

v0.3.0 for compatibility from TYPO3 6.2 to 8.7.

v9.0.0 for compatibility with TYPO3 9.5

I also added some functional tests to make sure the code from you example works for every version a expected.

Please let me know when you find any issues.

Kind regards
Alex
